[package]
name = "capnoise-server"

authors.workspace     = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
repository.workspace  = true
version.workspace     = true

publish = false
